site_name: AFF3CT-CORE
site_url: https://affec3ct-core-siteplaceholder.com/
theme:
  logo: assets/diagram-project-solid.svg
  features:
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer
  name: material
  palette:
    scheme: default
    primary: black
    secondary: black
    hljs_style: monokai   
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  language: en

repo_url: https://gitlab.lip6.fr/sog/aff3ct-core

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

plugins: 
  - search

extra_css:
  - css/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: 
    - index.md
  - Elementary Componenets:
      - module & task.md
      - Socket.md
      - Sequence & Subsequence.md
      - Pipeline & Adaptor.md
      - Switcher.md
  - New features : 
      - Forward socket.md
      - Control Flow.md